@URL=http://localhost:4000

@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZTVjMTFiZi1kNmNmLTRhMTctOWIzZS1lMTYzYWM5NjM5MzciLCJlbWFpbCI6ImJhbHV0YXJvY2s3MTExMTdAZ21haWwuY29tIiwiaWF0IjoxNzYzMjA1NDU0LCJleHAiOjE3NjMyMDkwNTR9.AjgfDT6X051j-Vs675R-F9rRwzLr2wDMUmxCTwhDHoU

###
GET {{URL}}/health
Content-Type: application/json

###
POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "email": "balutarock71117@gmail.com",
  "password": "Qwerty@123",
  "name": "balutarock"
}

###
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "email": "balutarock71117@gmail.com",
  "password": "Qwerty@123"
}

###
GET {{URL}}/api/plans
Content-Type: application/json


###
GET {{URL}}/api/subscriptions/my-subscription
Content-Type: application/json
Authorization: Bearer {{TOKEN}}



###
GET {{URL}}/api/admin/subscriptions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

##### TODO
###
GET {{URL}}/api/todo/
Content-Type: application/json

###
POST {{URL}}/api/todo/
Content-Type: application/json

{
  "title": "Test Todo",
  "isCompleted": false
}


###
PUT {{URL}}/api/todo/ed0d17b4-f3e1-4882-93cf-d4265d975948
Content-Type: application/json

{
  "title": "Updated Todo",
  "isCompleted": true
}


###
DELETE {{URL}}/api/todo/ed0d17b4-f3e1-4882-93cf-d4265d975948
Content-Type: application/json
